### ISSUE TITLE
abseil build fails on armv6

### ISSUE THREAD

**Issue by solsticedhiver** [mesonbuild/abseil-cpp#2]
I previously opened https://github.com/falconindy/auracle/issues/79

It appears **abseil** subproject fails with a linking error because `-latomic` is not defined (but this is weird because this only happens on **armv6 with g++**, not armv7)

I fixed the build issue by adding *libatomic* as a dependency to *abseil subproject* in *auracle* `meson.build`.

But going deeper into the problem, this seems to me a problem with the meson.build patch for abseil-cpp ? Someone even suggested it might be an issue with meson ?

One could may be fix the issue by changing the dependencies of abs_base_lib with (line 164)

     [dependency('threads'), cpp.find_library('atomic', required : false)]

or may even detect the cpu and add the dependency for atomic only on **arm** or **armv6** but this sounds more like a dirty hack

What do you think ? I am not an expert.

**Comment by jpakkane** [comment]
This is the simple fix that works everywhere, similarly to how math library is added with `cpp.find_library('m', required: false)`. The only downside is that it might add the atomic lib on some platforms where atomic is available but you don't need to specify it manually.

If you get this working, please file a pull request to fix it.

**Comment by falconindy** [comment]
Could we use the linker test from [this](https://github.com/termux/termux-packages/issues/3092) pull request? That would sort out cases where the platform needs libatomic in order to support `std::atomic<>`.

**Comment by solsticedhiver** [comment]
I was given this link on IRC: https://gitlab.freedesktop.org/mesa/mesa/-/blob/master/meson.build#L1121
this is MIT licensed. This tests for atomic and the need for `-latomic` or not.
