### ISSUE TITLE
How to make abseil-cpp externel project in meson?

### ISSUE THREAD

**Issue by shipleyxie** [mesonbuild/abseil-cpp#9]
How to make abseil-cpp externel project in meson?
And then I can link with my main project ...
Could you give me some suggestions ?

**Comment by eli-schwartz** [comment]
https://mesonbuild.com/Subprojects.html

Simply add the wrap file from https://wrapdb.mesonbuild.com/ into your project, then use subproject.get_variable() or dependency() fallbacks.

**Comment by shipleyxie** [comment]
I'm new to meson, Could you provide full demo code to use externel_project with meson ?

**Comment by eli-schwartz** [comment]
There is demo code in the first link. Is there anything specific that you're not sure about?

**Comment by shipleyxie** [comment]
After `git clone https://github.com/abseil/abseil-cpp.git` into `third_pary`, I copy [abseil-cpp meson.build](https://github.com/mesonbuild/abseil-cpp/blob/20200225.2/meson.build) In `third_party/abseil-cpp`.

add following line in my main project's meson.build 
```
absl_dep= subproject('third_party/abseil-cpp').get_variable()
```
got error as follows; 

> meson.build:52: WARNING: Subproject name has a path separator. This may cause unexpected behaviour.
> meson.build:52:0: ERROR: Neither a subproject directory nor a third_party/abseil-cpp.wrap file was found.

**Comment by eli-schwartz** [comment]
> All subprojects must be inside `subprojects` directory. The `subprojects` directory must be at the top level of your project. Subproject declaration must be in your top level `meson.build`.

Note the `libsimple` example instructs you to clone into subprojects/libsimple/ and use `subproject('libsimple').get_variable('libsimple_dep')`, so you do not specify the directory...

**Comment by eli-schwartz** [comment]
See also https://mesonbuild.com/Using-the-WrapDB.html for installing a wrap from the wrapdb. Also, https://mesonbuild.com/Using-wraptool.html
